#!/usr/bin/env python

Import("env")
Import("env_modules")

env_renderdoc = env_modules.Clone()

env_renderdoc.Prepend(CPPPATH=["#thirdparty/renderdoc"])

# Godot's own source files

module_obj = []

env_renderdoc.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj
